name: example

description: Demonstrates how to use the flutter_in_store_app_version_checker package to check for app updates on Google Play and App Store.

publish_to: none

version: 0.0.1


environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.9"


dependencies:
  flutter:
    sdk: flutter

  flutter_in_store_app_version_checker:
    path: ../

  cupertino_icons: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
