name: flutter_in_store_app_version_checker

description: A lightweight flutter plugin to check if your app is up-to-date on GooglePlay or AppStore

version: 2.0.0-pre.16

homepage: https://github.com/ziqq/flutter_in_store_app_version_checker

repository: https://github.com/ziqq/flutter_in_store_app_version_checker

issue_tracker: https://github.com/ziqq/flutter_in_store_app_version_checker/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://boosty.to/ziqq

platforms:
  android:
  ios:

#screenshots:
#  - description: 'Example of using the library to check app version.'
#    path: example.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Http
  http: ^1.6.0

  # Utilities  # Annotations
  meta: ^1.9.1
  package_info_plus: ^9.0.0

dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Utilities
  collection: any

  # Logging
  l: ^5.0.1

  build_runner: ^2.9.0

  # Testing
  mockito: ^5.5.1

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.instoreappversionchecker
        pluginClass: InStoreAppVersionCheckerPlugin
      ios:
        pluginClass: InStoreAppVersionCheckerPlugin
