/*
 * Author: Anton Ustinoff <https://github.com/ziqq> | <a.a.ustinoff@gmail.com>
 * Date: 28 October 2025
 */

import 'package:meta/meta.dart';

/// {@template android_store}
/// Possible types of android store
/// {@endtemplate}
enum InStoreAppVersionChecker$AndroidStore {
  /// The default AAB
  googlePlayStore,

  /// The pure APK
  apkPure
}

/// {@template in_store_app_version_checker_params}
/// Params for [InStoreAppVersionChecker].
/// {@endtemplate}
@immutable
class InStoreAppVersionChecker$Params {
  /// {@macro in_store_app_version_checker_params}
  const InStoreAppVersionChecker$Params({
    required this.locale,
    this.packageName,
    this.currentVersion,
    this.androidStore = InStoreAppVersionChecker$AndroidStore.googlePlayStore,
  });

  /// The locale your app store.
  final String locale;

  /// The package name of the app `com.exemple.your_app`.
  ///
  /// - `bundleIdentifier` on iOS and macOS.
  ///   Defined in the product target in xcode.
  /// - `packageName` on Android.
  ///   Defined in `build.gradle` as `applicationId`.
  /// - `package_name` from `version.json` on Web and Linux
  ///   Generated by Flutter.
  ///
  /// If [appID] is null the [appID] will take the Flutter package identifier.
  final String? packageName;

  /// The current version of the app.
  /// If [currentVersion] is null, it is taked from the Flutter package version.
  final String? currentVersion;

  /// The android store type of the app to check.
  /// Default `InStoreAppVersionChecker$AndroidStore.GooglePlayStore`.
  final InStoreAppVersionChecker$AndroidStore androidStore;
}
