/*
 * Author: Anton Ustinoff <https://github.com/ziqq> | <a.a.ustinoff@gmail.com>
 * Date: 28 October 2025
 */

import 'package:meta/meta.dart';

/// {@template in_store_app_version_checker_android_store_type}
/// Available Android store sources.
/// {@endtemplate}
enum InStoreAppVersionCheckerAndroidStoreType {
  /// Google Play Store.
  googlePlayStore,

  /// ApkPure.
  apkPure,
}

/// {@template in_store_app_version_checker_params}
/// Parameters for [InStoreAppVersionChecker].
/// {@endtemplate}
@immutable
class InStoreAppVersionCheckerParams {
  /// {@macro in_store_app_version_checker_params}
  const InStoreAppVersionCheckerParams({
    required this.locale,
    this.packageName,
    this.currentVersion,
    this.androidStore =
        InStoreAppVersionCheckerAndroidStoreType.googlePlayStore,
  });

  /// The locale used for store requests.
  final String locale;

  /// The package name of the app, for example `com.example.your_app`.
  ///
  /// - `bundleIdentifier` on iOS and macOS.
  ///   Defined in the product target in Xcode.
  /// - `packageName` on Android.
  ///   Defined in `build.gradle` as `applicationId`.
  /// - `package_name` from `version.json` on Web and Linux.
  ///   Generated by Flutter.
  ///
  /// If [packageName] is null, the installed app package identifier is used.
  final String? packageName;

  /// The current version of the app.
  /// If [currentVersion] is null, the installed app version is used.
  final String? currentVersion;

  /// The Android store source to check.
  /// Default `InStoreAppVersionCheckerAndroidStoreType.googlePlayStore`.
  final InStoreAppVersionCheckerAndroidStoreType androidStore;
}
