/*
 * Author: Anton Ustinoff <https://github.com/ziqq> | <a.a.ustinoff@gmail.com>
 * Date: 28 October 2025
 */

import 'package:meta/meta.dart';

/// {@template in_store_app_version_checker_android_store_type}
/// Available Android store sources.
/// {@endtemplate}
enum InStoreAppVersionCheckerAndroidStoreType {
  /// Google Play Store.
  googlePlayStore,

  /// ApkPure.
  apkPure,

  /// VK RuStore.
  ruStore,

  /// Huawei AppGallery public web listing.
  ///
  /// This mode supports arbitrary applications and requires
  /// [InStoreAppVersionCheckerParams.storeID].
  appGallery,

  /// Huawei AppGallery native update check for the installed application.
  ///
  /// This mode uses Huawei `AppUpdateClient` and does not support package or
  /// version overrides.
  appGalleryNative,
}

/// {@template in_store_app_version_checker_params}
/// Parameters for [InStoreAppVersionChecker].
/// {@endtemplate}
@immutable
class InStoreAppVersionCheckerParams {
  /// {@macro in_store_app_version_checker_params}
  const InStoreAppVersionCheckerParams({
    required this.locale,
    this.packageName,
    this.storeID,
    this.currentVersion,
    this.androidStore =
        InStoreAppVersionCheckerAndroidStoreType.googlePlayStore,
  });

  /// The locale used for store requests, for example `en-US` or `zh-Hant-TW`.
  ///
  /// Regional locales accept hyphens or underscores, with case normalized.
  /// Google Play receives the complete locale as its `hl` parameter; a
  /// language-only value such as `en` is also supported there.
  ///
  /// On iOS, the two-letter region selects the App Store storefront.
  /// Country-only values such as `us`, `ae`, and `ru` remain supported.
  /// Short values are always interpreted as countries on iOS: `ar` means
  /// Argentina, while `ar-AE` selects the UAE storefront. A language such as
  /// `en` is not a country and must not be used alone on iOS.
  ///
  /// iOS accepts `language-REGION`, `language-Script-REGION`, or a two-letter
  /// country code. Script-only locales, numeric regions, variants, and
  /// extensions are not supported on iOS. Apple validates storefront
  /// availability; a valid format does not guarantee a supported country.
  /// No country is inferred from the language and no fallback country is used.
  /// ApkPure ignores this value.
  final String locale;

  /// The package name of the app, for example `com.example.your_app`.
  ///
  /// - `bundleIdentifier` on iOS and macOS.
  ///   Defined in the product target in Xcode.
  /// - `packageName` on Android.
  ///   Defined in `build.gradle` as `applicationId`.
  /// - `package_name` from `version.json` on Web and Linux.
  ///   Generated by Flutter.
  ///
  /// If [packageName] is null, the installed app package identifier is used.
  final String? packageName;

  /// The identifier of the application listing in the selected store.
  ///
  /// AppGallery web checks require an ID such as `C107631977`. Stores whose
  /// listing identifier is the Android package name do not require this value.
  /// AppGallery native checks identify the installed application through the
  /// official Huawei SDK and ignore this value.
  final String? storeID;

  /// The current version of the app.
  /// If [currentVersion] is null, the installed app version is used.
  final String? currentVersion;

  /// The Android store source to check.
  /// Default `InStoreAppVersionCheckerAndroidStoreType.googlePlayStore`.
  final InStoreAppVersionCheckerAndroidStoreType androidStore;
}
